"""Initial Migration

Revision ID: 6fd8cac9f91f
Revises: 09eae8a0b62a
Create Date: 2022-05-17 10:11:52.184814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fd8cac9f91f'
down_revision = '09eae8a0b62a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blogger_name', sa.String(), nullable=True))
    op.add_column('blogs', sa.Column('blog_context', sa.String(), nullable=True))
    op.drop_column('blogs', 'blog_review')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog_review', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'blog_context')
    op.drop_column('blogs', 'blogger_name')
    # ### end Alembic commands ###
