"""Initial Migration

Revision ID: 733cb728e372
Revises: b734feaad5f8
Create Date: 2022-05-16 18:02:28.084586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733cb728e372'
down_revision = 'b734feaad5f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_secure')
    # ### end Alembic commands ###
