"""Initial Migration

Revision ID: 79081df7545a
Revises: d85cc96c27a8
Create Date: 2022-05-18 02:53:44.157885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79081df7545a'
down_revision = 'd85cc96c27a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('blog_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'roles', ['blog_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'blog_id')
    # ### end Alembic commands ###
